package com.achievix.goal.dto;

import com.achievix.task.dto.TaskDTO;
import jakarta.validation.constraints.*;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Data
public class GoalDetailsDTO {
    // should be generated by the database
    @NotNull
    @Positive(message = "ID must be a positive number")
    private Long id;

    @NotBlank(message = "Title cannot be blank")
    private String title;

    // is being set and updated by the service
    // 0 means not started >0 means in progress
    @NotNull(message = "Target value cannot be null")
    @PositiveOrZero(message = "Target value must be a positive number")
    private Integer targetValue;

    // is being set and updated by the service
    @NotNull(message = "Current value cannot be null")
    @PositiveOrZero(message = "Current value must be a positive number")
    private Integer currentValue;

    @FutureOrPresent(message = "Deadline must be in the present or future")
    private LocalDate deadline;

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    //list of task dto
    private List<TaskDTO> tasks;
}
